openapi: 3.0.3
info:
  title: Travel Planner API
  description: A simple Travel Planner API
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local development server

paths:
  /trips:
    get:
      summary: Get all trips
      operationId: getAllTrips
      tags:
        - Trips
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Trip'
    post:
      summary: Add Trip
      operationId: addTrip
      tags:
        - Trips
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Trip'
      responses:
        '201':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Trip'
  /trips/{tripId}:
    get:
      summary: Get trip by ID
      operationId: getTripById
      tags:
        - Trips
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Trip'


components:
  schemas:
    Trip:
      type: object
      required:
        - title
        - startDate
        - endDate
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date

tags:
  - name: Trips
    description: Operations (CRUD) for trips